version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "sneeom"
github_repo = "samrepo"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev-pipeline.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::206572126289:role/webIdentityCustomRole"
cloudformation_execution_role = "arn:aws:iam::206572126289:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-tXT8uoaDDz5n"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-p-artifactsbucket-l1ewc3izwnq1"
image_repository = ""
region = "us-west-2"

[prod-pipeline.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::206572126289:role/webIdentityCustomRole"
cloudformation_execution_role = "arn:aws:iam::206572126289:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-1iVQzZsBYpiW"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-ofaolibhtqtv"
image_repository = ""
region = "us-east-1"
